# parameterRepo

## theta[2] < theta[1]

1. Basic algebraic computation for fixed point and eigenvalues.

2. PaperCodeV1 T2 < T1.ipynb generates algebraic decomposition of parameter space, the adjacency of parameter regions and 1000 sample points for each parameter region. It also generates the adjacent graph of parameter regions.

3. gdAnalysis21.ipynb analyzes the asymmetric design for the 1000 parameters over each parameter regions.

4. isCylindricalT2sT1.nb check whether a given semi algebraic set (covering set or intersection of covering set) is cylindrical or not. Used in the proof of simply connectedness of the parameter decomposition. 

5. finalplot21.gv is the adjacent graph file. Edge information is from PaperCodeV1 T2 < T1.ipynb.

6. projectedSetV1T21.csv: the set of semi algebraic set that we need to check isCylindrical.It is generated by PaperCodeV1 T2 < T1.ipynb and is the input to isCylindricalT2sT1.nb.

## theta[1] < theta[2]

It is symmetric as above.


